### ISSUE TITLE
Reverse depends on not working for Source Dependency Walker

### ISSUE THREAD

**Issue by tspicer01** [ros-infrastructure/rosdistro#105]
The get_depends_on and get_recursive_depends_on are not working for a SourceDependencyWalker.
The functions are trying to pull the repo from the release_repository which in our case doesn't exist as we have only the source.

Proposal
Have a new function _get_repo that can be used internally and overridden in the SourceDependencyWalker to return the repo depending on the object that is being used.  This will allow for the SourceDependencyWalker to use the parent functions.

**Comment by dirk-thomas** [comment]
Addressed by #106.
