### ISSUE TITLE
Wrap source repo package xmls in an object

### ISSUE THREAD

**Issue by mikepurvis** [ros-infrastructure/rosdistro#116]
Right now when you call `get_source_repo_package_xmls`, you get back the dict directly from the cache, but this is sucky because in order to iterate it you have to manually remove the `_ref` key that stores the SHA of the repo at the time the cache was captured.

Rather, there should be a `SourceRepoCache` object returned that implements `__getitem__`, `__iter__`, `__len__`, `keys` to expose the XML strings, but has a separate interface for getting the git reference information.

Prompted by the confusion in this discussion: https://github.com/ros-infrastructure/rosinstall_generator/pull/44#discussion_r169417262

**Comment by dirk-thomas** [comment]
Addressed by #117.
