### ISSUE TITLE
DependencyWalker._get_dependencies() fails to get <depends>

### ISSUE THREAD

**Issue by KenYN** [ros-infrastructure/rosdistro#131]
If we are using v2 format, the code at https://github.com/ros-infrastructure/rosdistro/blob/master/src/rosdistro/dependency_walker.py#L120

    deps = {
        'buildtool': pkg.buildtool_depends,
        'build': pkg.build_depends,
        'run': pkg.run_depends,
        'test': pkg.test_depends
    }

Misses out plain `<depend>` packages.

**Comment by KenYN** [comment]
Hmm, not a bug I think...

**Comment by dirk-thomas** [comment]
`depends` are already expanded into `build_depends`, `build_export_depends` and `exec_depends`. The API doesn't even expose them as such. So this is certainly not the reason for whatever problem you are looking into.

See https://github.com/ros-infrastructure/catkin_pkg/blob/e4b9bcd884b5f7fb9e6ddcfaa976aa3c72c22654/src/catkin_pkg/package.py#L91-L95

**Comment by KenYN** [comment]
Note the real issue is https://github.com/ros-infrastructure/rosinstall_generator/issues/53#issue-420843088 - I just jumped the gun with this report.
