### ISSUE TITLE
Insecure tempfile

### ISSUE THREAD

**Issue by danielwangksu** [ros-infrastructure/rosdistro#137]
Functions that create temporary file names (such as tempfile.mktemp and os.tempnam) are fundamentally insecure, as they do not ensure exclusive access to a file with the temporary name they return. The file name returned by these functions is guaranteed to be unique on creation but the file must be opened in a separate operation. There is no guarantee that the creation and open operations will happen atomically. This provides an opportunity for an attacker to interfere with the file before it is opened.
https://github.com/ros-infrastructure/rosdistro/blob/2565c2c5e4add200dc8828d738e7c3d2c1850485/scripts/rosdistro_convert#L196

Replace the use of mktemp with some of the more secure functions in the tempfile module, such as TemporaryFile. If the file is intended to be accessed from other processes, consider using the NamedTemporaryFile function.

**Comment by dirk-thomas** [comment]
The conversion script the `mktemp` function is being used is only invoked rarely by users to convert already EOL distro files from an old format. Therefore I don't think the following argument is relevant here:

> This provides an opportunity for an attacker to interfere with the file before it is opened.

I will go ahead and close this. If you think this should still be changed please feel free to provide a pull request.
