### ISSUE TITLE
Argument number does not match

### ISSUE THREAD

**Issue by danielwangksu** [ros-infrastructure/rosdistro#138]
`_yaml_header_lines` requires 2 argument
https://github.com/ros-infrastructure/rosdistro/blob/2565c2c5e4add200dc8828d738e7c3d2c1850485/scripts/rosdistro_migrate_to_rep_141#L152

https://github.com/ros-infrastructure/rosdistro/blob/2565c2c5e4add200dc8828d738e7c3d2c1850485/src/rosdistro/verify.py#L160

**Comment by dirk-thomas** [comment]
Please consider to provide a pull request to address the problem.
