### ISSUE TITLE
Incomplete URL substring sanitization

### ISSUE THREAD

**Issue by danielwangksu** [ros-infrastructure/rosdistro#140]
"evil-example.net/github.com" is accepted
https://github.com/ros-infrastructure/rosdistro/blob/2565c2c5e4add200dc8828d738e7c3d2c1850485/src/rosdistro/manifest_provider/github.py#L59

https://github.com/ros-infrastructure/rosdistro/blob/2565c2c5e4add200dc8828d738e7c3d2c1850485/src/rosdistro/manifest_provider/github.py#L79

**Comment by mikepurvis** [comment]
True, but looking at the rest of those functions, all it does is plug over pieces of those strings into `raw.githubusercontent.com` and `api.github.com` URLs. It's only supposed to be a heuristic, not a validation.

I think this is harmless, but feel free to send a fix/improvement if you desire.

**Comment by danielwangksu** [comment]
> True, but looking at the rest of those functions, all it does is plug over pieces of those strings into `raw.githubusercontent.com` and `api.github.com` URLs. It's only supposed to be a heuristic, not a validation.
> 
> I think this is harmless, but feel free to send a fix/improvement if you desire.

Yes @mikepurvis  you are right. I will try to come up with something. But I agree this is totally fine for the purpose. Thank you for your response

**Comment by dirk-thomas** [comment]
@danielwangksu Are you still planning to work on this?
