### ISSUE TITLE
release generates invalid dependency on python3-setuptools in deb package

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/rosdistro#15]
On precise, the package python-rosdistro has a dependency on python3-setuptools | python-setuptools, and if setuptools is not already installed, the first one will be installed, resulting on python3 being installed. This is not critical, but this behavior is not desirable.

Below the control file of the debian package:
```
Package: python-rosdistro
Source: rosdistro
Version: 0.2.8-1
Architecture: all
Maintainer: Dirk Thomas <dthomas@osrfoundation.org>
Installed-Size: 276
Depends: python (>= 2.6), python-support (>= 0.90.0), python-argparse, python-catkin-pkg, python-rospkg, python-yaml, python3-setuptools | py
thon-setuptools
Provides: python2.6-rosdistro
Section: python
Priority: optional
Description: A tool to work with rosdistro files
 A tool to work with rosdistro files
Python-Version: 2.6
```

**Comment by dirk-thomas** [comment]
The current Debian package does not have that problem anymore.
