### ISSUE TITLE
Package format 2 support

### ISSUE THREAD

**Issue by mikepurvis** [ros-infrastructure/rosdistro#67]
The state of package with respect to REP-140 is not clear to me, specifically DependencyWalker (which is in turn used by `rosinstall_generator`).

The also package.xml parsing is delegate to the format2-aware [catkin_pkg.parse_package_string](https://github.com/ros-infrastructure/catkin_pkg/blob/f331a66cc23220179fc9db2f8797ceaad5b73ab8/src/catkin_pkg/package.py#L376), but then the current implementation of _get_dependencies is unaware of doc_depends, depends, exec_depends, libexec_depends:

https://github.com/ros-infrastructure/rosdistro/blob/master/src/rosdistro/dependency_walker.py#L116

Is there a translation layer here which I'm not seeing, or is this an implementation gap?

**Comment by dirk-thomas** [comment]
`catkin_pkg` can parse manifests with both format version. But the exposed API is the same. The dependency walker uses e.g. `run_depend` which in format 2 can be an `exec_depend`.

doc dependencies on the other hand are not used for topological order. They only provide a way to specify additional dependencies necessary to generate documentation, e.g. latex.

**Comment by wjwwood** [comment]
`run_depend` is both `exec_depend` and `build_export_depend`: https://github.com/ros-infrastructure/catkin_pkg/blob/master/src/catkin_pkg/package.py#L108-L113

**Comment by mikepurvis** [comment]
Got it. The `__getattr__` magic had me fooled. Sorry for the noise.
