### ISSUE TITLE
remove deprecated API

### ISSUE THREAD

**Issue by dirk-thomas** [ros-infrastructure/rosdistro#87]
Specifically the API which can't operate anymore with REP 143 deployed and the build information being removed from the rosdistro repo.

**Comment by mikepurvis** [comment]
Assuming this is referring to all the release_* files, a big +1 from me. There's a lot of duplication at present which can make it pretty hard to reason about what's going on in this repo.

**Comment by dirk-thomas** [comment]
Instead of removing them they have been moved into a separate module. That keeps backward compatibility but moves the API "out of view".
